apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  destination:
    name: ''
    namespace: databases
    server: 'https://kubernetes.default.svc'
  project: k8s
  syncPolicy: {}
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mongodb
    targetRevision: 16.5.29
    helm:
      valueFiles:
      - $values/db/mongodb/values.yaml
  - repoURL: 'https://github.com/tzcnysf/argocd.git'
    targetRevision: main
    ref: values
