global:
  postgresql:
    auth:
      existingSecret: "postgresql-secrets"
architecture: standalone
primary:
  persistence:
    size: 10Gi
  resources:
    limits:
      cpu: "4"
      memory: 4Gi
    requests:
      cpu: "4"
      memory: 4Gi      
  initdb:
    scriptsSecret: postgres-init-secrets
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: platform
            operator: In
            values:
            - databases 
